### basic settings

# site properties and page defaults
title: Stajich Laboratory for Fungal Evolutionary Genomics
description: An easy-to-use, flexible website template for labs, with automatic citations, GitHub tag imports, pre-built components, and more.
logo: images/logo.svg
header: images/backgrounds/mojave_cholla_background.jpg
footer: images/backgrounds/mojave_cholla_background.jpg
baseurl: /

# site social media and other links
links:
  email: jason.stajich@ucr.edu
  google-scholar: Jason Stajich
  github: stajichlab
  twitter: stajichlab
  instagram: stajichlab
  youtube: stajichlab

# automatic citations
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
  output: ../_data/citations.yaml

### advanced settings

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-github-metadata
  # - jekyll-avatar
  - jekyll-gist
  - jekyll-mentions
  - jekyll-relative-links
    #- jemoji

# jekyll theme
theme: null
